apiVersion: apps/v1
kind: Deployment
metadata:
  name: iti-task
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ITI
  template:
    metadata:
      labels:
        app: ITI
    spec:
      containers:
      - name: web-patient
        image: mohamedezzat1/iti-actions:3 
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: service-web
spec:
  type: NodePort
  selector:
    app: ITI
  ports:
    - port: 6000
      targetPort: 8000
      nodePort: 32000   
